name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run your script
        env:
          GH_API_KEY: ${{ secrets.GH_API_KEY }}
        run: |
          # Пример использования API
          curl -H "Authorization: token $GH_API_KEY" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/OWNER/REPO/contents/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
